In [2]:
import numpy as np
import numpy.linalg as la

In [3]:
kac = 1.
Eac = 0.1
V0 = 1.
kbc =1.

In [9]:
Omega = np.zeros((3,3),dtype=float)
Omega[0,0] = - (kac+1)*np.exp(V0)
Omega[0,1] = 1
Omega[0,2] = kac*np.exp(-Eac)
Omega[1,0] = np.exp(V0)
Omega[1,1] =-kbc-1
Omega[1,2] = kbc
Omega[2,0] =kac*np.exp(V0)
Omega[2,1] = kbc
Omega[2,2] = -kac*np.exp(-Eac)-kbc
print(Omega)
print(np.sum(Omega,axis=0))

[[-5.43656366  1.          0.90483742]
 [ 2.71828183 -2.          1.        ]
 [ 2.71828183  1.         -1.90483742]]
[0. 0. 0.]


In [21]:
ra_no_norm = kac * np.exp(-Eac) * 1 + kbc*1 + kbc*kac*np.exp(-Eac)
rb_no_norm = kac*np.exp(-Eac)*np.exp(0)+np.exp(0)*kbc+kac*np.exp(0)*kbc
rc_no_norm = kac*np.exp(0)*kbc+1*kac*np.exp(0)+np.exp(0)*kbc
S = ra_no_norm+rb_no_norm+rc_no_norm
ra_infty = ra_no_norm/S
rb_infty = rb_no_norm/S
rc_infty = rc_no_norm/S

rho_0 = np.array([0,ra_infty,0,rb_infty,0,rc_infty])
ra_inf_nonorm = kac * np.exp(-Eac) * 1 + kbc*1 + kbc*kac*np.exp(-Eac)
rb_inf_nonorm = kac*np.exp(-Eac)*np.exp(V0)+np.exp(V0)*kbc+kac*np.exp(V0)*kbc
rc_inf_nonorm = kac*np.exp(V0)*kbc+1*kac*np.exp(V0)+np.exp(V0)*kbc
S = ra_inf_nonorm+rb_inf_nonorm+rc_inf_nonorm
rainfty = ra_inf_nonorm/S
rbinfty = rb_inf_nonorm/S
rcinfty = rc_inf_nonorm/S

rho_eq = np.zeros(3,dtype=float)
rho_eqV = np.zeros(3,dtype=float)
rho_eq[0] = ra_infty
rho_eqV[0] = rainfty
rho_eq[1] = rb_infty
rho_eqV[1] = rbinfty
rho_eq[2] = rc_infty
rho_eqV[2] = rcinfty

print(rho_eqV)

[0.14896991 0.41865743 0.43237266]


In [11]:
np.dot(Omega,rho_eqV)

array([-1.19910833e-16,  1.11022302e-16, -4.66226208e-17])

In [38]:
v,w = la.eig(Omega)
for i in range(v.shape[0]):
    w[:,i] = w[:,i]/sum(abs(w[:,i]))

In [39]:
print(v)
print(w)


[-6.38964103e+00 -1.80411242e-16 -2.95176004e+00]
[[-0.5         0.14896991 -0.01365394]
 [ 0.25346074  0.41865743 -0.48634606]
 [ 0.24653926  0.43237266  0.5       ]]


In [18]:
print(w[2]-rho_eqV)

[0.25361416 0.27870677 0.28431659]


In [28]:
w

array([[-0.81647051,  0.24027024, -0.01957126],
       [ 0.41388643,  0.67524321, -0.69711799],
       [ 0.40258407,  0.6973642 ,  0.71668925]])

array([0.14896991, 0.41865743, 0.43237266])